### ISSUE TITLE
100% trash

### ISSUE THREAD

**Issue by BookieBee** [JoXW100/TehsStardewValleyMods#1]
I am only getting 100% trash. It shows in the UI that the only chance is for trash and i am actually only fishing up trash. All days all weather. I tried adjusting the settings but that didn't do anything. There are no errors in SMAPI to show...

**Comment by JoXW100** [comment]
@BookieBee 
- What location does this happen in? 
- Do you get the same without any other mods?
- Are you playing on steamdeck/pc etc?
- What settings are you using, and does reseting them to the default help?
- Are you using a new or old (pre 1.6) save?

**Comment by BookieBee** [comment]
All fishable locations around town. I haven't tried in the mines yet.
It is the same whether I have other mods or just this one.
I'm playing on PC.
I was mostly using the default settings for the mod, but I also tried adjusting them. I can't remember exactly what I tried changing.
I was just using it on new saves. I can try it on a pre 1.6 save this evening.

**Comment by JoXW100** [comment]
@BookieBee,  I managed to find a cause, try testing the latest release.
